name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Verify Railway CLI Installation
        run: |
          which railway || echo "Railway CLI not found in PATH"
          railway --version || echo "Railway CLI version check failed"

      - name: Deploy to Railway
        run: |
          echo "🚀 Deploying to Railway..."
          railway up --detach || {
            echo "❌ Railway deployment failed"
            echo "Checking Railway CLI status..."
            railway whoami || echo "Not authenticated to Railway"
            exit 1
          }
          echo "✅ Railway deployment initiated"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
